### ISSUE TITLE
Credit Card Coverage TODO List

### ISSUE THREAD

**Issue by keithkade** [keithkade/keithkade.github.io#15]
- [ ] Better docs / contribution guide
Especially for people who want to add / update cards

- [ ] Page metadata
Make sure this is decent

- [ ] Style the page 
Basic responsive layout and spacing

- [ ] Support for user-added custom cards
Build a UI where users can enter and save a new card. Would need to name the card, specify rewards per category, and specify what type of rewards that card has. Preferably we use local storage to remember cards the user has added between sessions. 

- [ ] Display custom point values and allow editing
Logic is already there to use custom point values when computing rewards, just need to hook it up to some UI

- [ ] Support support subcategory relationships
Example. Amazon is part of online shopping. So if a card gives X % on online shopping, Amazon should be included

- [ ] Show / Hide categories
Category list is gonna get long, so need some UI to show / hide rows

- [ ] Support cards with where you pick two custom categories (US Bank Cash Plus)
https://cashplus.usbank.com

- [ ] Allow users to specify their Bank of America rewards tier and update BofA cards accordingly 
https://www.bankofamerica.com/preferred-rewards/

- [ ] "Best to use for X" report
After users have entered all their cards, nicely tell them what the best card to use for each category is

- [ ] Card recommendations
Users should be able to select a category, and we recommend them the best card based on the cards and info about the user we have.

- [ ] Spending caps
Not sure exactly what to do here, but I figure we should at least display this info. Maybe allow users to ignore cards with spending caps below a certain level.
